"""add model column to conversations

Revision ID: 272a03552c78
Revises: cd7cc3eddba3
Create Date: 2025-11-05 19:23:28.005929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272a03552c78'
down_revision: Union[str, Sequence[str], None] = 'cd7cc3eddba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_channel_conversations_updated_at'), table_name='channel_conversations')
    op.create_index('idx_channel_conversations_updated_at', 'channel_conversations', ['updated_at'], unique=False, postgresql_ops={'updated_at': 'DESC'})
    op.drop_constraint(op.f('uq_channel_user'), 'channel_conversations', type_='unique')
    op.create_index('uq_channel_user', 'channel_conversations', ['channel_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_channel_conversations_channel_id'), 'channel_conversations', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_conversations_user_id'), 'channel_conversations', ['user_id'], unique=False)
    op.drop_constraint(op.f('uq_channel_video'), 'channel_videos', type_='unique')
    op.create_index('uq_channel_video', 'channel_videos', ['channel_id', 'transcript_id'], unique=True)
    op.create_index(op.f('ix_channel_videos_channel_id'), 'channel_videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_videos_transcript_id'), 'channel_videos', ['transcript_id'], unique=False)
    op.alter_column('channels', 'qdrant_collection_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Sanitized collection name for Qdrant',
               existing_comment='Sanitized collection name',
               existing_nullable=False)
    op.drop_constraint(op.f('channels_name_key'), 'channels', type_='unique')
    op.drop_index(op.f('idx_channels_is_active'), table_name='channels')
    op.drop_index(op.f('idx_channels_name'), table_name='channels')
    op.drop_index(op.f('idx_channels_qdrant_collection'), table_name='channels')
    op.create_index(op.f('ix_channels_is_active'), 'channels', ['is_active'], unique=False)
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=True)
    op.create_index(op.f('ix_channels_qdrant_collection_name'), 'channels', ['qdrant_collection_name'], unique=False)
    op.alter_column('chunks', 'channel_id',
               existing_type=sa.UUID(),
               comment='Denormalized for fast channel chunk lookups.',
               existing_nullable=True)
    op.drop_index(op.f('idx_chunks_channel_id'), table_name='chunks')
    op.create_index(op.f('ix_chunks_channel_id'), 'chunks', ['channel_id'], unique=False)
    op.add_column('conversations', sa.Column('model', sa.String(length=50), server_default='claude-haiku-4.5', nullable=False))
    op.create_index(op.f('ix_conversations_model'), 'conversations', ['model'], unique=False)
    op.drop_index(op.f('idx_messages_channel_conversation_id'), table_name='messages')
    op.create_index(op.f('ix_messages_channel_conversation_id'), 'messages', ['channel_conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_channel_conversation_id'), table_name='messages')
    op.create_index(op.f('idx_messages_channel_conversation_id'), 'messages', ['channel_conversation_id'], unique=False)
    op.drop_index(op.f('ix_conversations_model'), table_name='conversations')
    op.drop_column('conversations', 'model')
    op.drop_index(op.f('ix_chunks_channel_id'), table_name='chunks')
    op.create_index(op.f('idx_chunks_channel_id'), 'chunks', ['channel_id'], unique=False)
    op.alter_column('chunks', 'channel_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Denormalized for fast channel chunk lookups.',
               existing_nullable=True)
    op.drop_index(op.f('ix_channels_qdrant_collection_name'), table_name='channels')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_index(op.f('ix_channels_is_active'), table_name='channels')
    op.create_index(op.f('idx_channels_qdrant_collection'), 'channels', ['qdrant_collection_name'], unique=False)
    op.create_index(op.f('idx_channels_name'), 'channels', ['name'], unique=True)
    op.create_index(op.f('idx_channels_is_active'), 'channels', ['is_active'], unique=False)
    op.create_unique_constraint(op.f('channels_name_key'), 'channels', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('channels', 'qdrant_collection_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Sanitized collection name',
               existing_comment='Sanitized collection name for Qdrant',
               existing_nullable=False)
    op.drop_index(op.f('ix_channel_videos_transcript_id'), table_name='channel_videos')
    op.drop_index(op.f('ix_channel_videos_channel_id'), table_name='channel_videos')
    op.drop_index('uq_channel_video', table_name='channel_videos')
    op.create_unique_constraint(op.f('uq_channel_video'), 'channel_videos', ['channel_id', 'transcript_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_channel_conversations_user_id'), table_name='channel_conversations')
    op.drop_index(op.f('ix_channel_conversations_channel_id'), table_name='channel_conversations')
    op.drop_index('uq_channel_user', table_name='channel_conversations')
    op.create_unique_constraint(op.f('uq_channel_user'), 'channel_conversations', ['channel_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_channel_conversations_updated_at', table_name='channel_conversations', postgresql_ops={'updated_at': 'DESC'})
    op.create_index(op.f('idx_channel_conversations_updated_at'), 'channel_conversations', [sa.literal_column('updated_at DESC')], unique=False)
    # ### end Alembic commands ###
