"""fix: change youtube_video_id unique constraint to composite (user_id, youtube_video_id)

Revision ID: 2b4a2190f4a6
Revises: 9660aa8618fd
Create Date: 2025-10-21 05:53:51.503078

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2b4a2190f4a6'
down_revision: Union[str, Sequence[str], None] = '9660aa8618fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_youtube_video_id'), table_name='transcripts')
    op.create_index(op.f('ix_transcripts_youtube_video_id'), 'transcripts', ['youtube_video_id'], unique=False)
    op.create_index('unique_user_video', 'transcripts', ['user_id', 'youtube_video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_user_video', table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_youtube_video_id'), table_name='transcripts')
    op.create_index(op.f('ix_transcripts_youtube_video_id'), 'transcripts', ['youtube_video_id'], unique=True)
    # ### end Alembic commands ###
