"""add_subscription_and_usage_tracking_tables

Revision ID: 526b978706b1
Revises: ccbac5e5315e
Create Date: 2025-12-28 21:04:56.870397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '526b978706b1'
down_revision: Union[str, Sequence[str], None] = 'ccbac5e5315e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Unique plan identifier: free, pro, enterprise'),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('stripe_price_id_monthly', sa.String(length=100), nullable=True, comment='Stripe Price ID for monthly billing'),
    sa.Column('stripe_price_id_annual', sa.String(length=100), nullable=True, comment='Stripe Price ID for annual billing'),
    sa.Column('monthly_price_cents', sa.Integer(), server_default='0', nullable=False, comment='Price in cents: 1200 = $12.00'),
    sa.Column('annual_price_cents', sa.Integer(), nullable=True, comment='Annual price in cents: 11500 = $115.00'),
    sa.Column('video_limit', sa.Integer(), nullable=True, comment='Max videos per month. NULL = unlimited'),
    sa.Column('message_limit', sa.Integer(), nullable=True, comment='Max messages per month. NULL = unlimited'),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False, comment='Feature flags for this plan'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_table('usage_tracking',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False, comment='Start of billing period'),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False, comment='End of billing period'),
    sa.Column('videos_used', sa.Integer(), server_default='0', nullable=False, comment='Videos loaded this period'),
    sa.Column('messages_used', sa.Integer(), server_default='0', nullable=False, comment='Messages sent this period'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_tracking_user_id'), 'usage_tracking', ['user_id'], unique=False)
    op.create_index('uq_user_period', 'usage_tracking', ['user_id', 'period_start'], unique=True)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True, comment='Stripe Customer ID'),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True, comment='Stripe Subscription ID'),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False, comment='active, trialing, past_due, canceled, enterprise'),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True, comment='Start of current billing period'),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True, comment='End of current billing period'),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='If true, subscription cancels at period end'),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True, comment='End of trial period if applicable'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'trialing', 'past_due', 'canceled', 'enterprise')", name='check_subscription_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_plan_id'), 'user_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_status'), 'user_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_stripe_customer_id'), 'user_subscriptions', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_stripe_subscription_id'), 'user_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=True)
    op.drop_index(op.f('idx_channel_conversations_updated_at'), table_name='channel_conversations')
    op.create_index('idx_channel_conversations_updated_at', 'channel_conversations', ['updated_at'], unique=False, postgresql_ops={'updated_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_channel_conversations_updated_at', table_name='channel_conversations', postgresql_ops={'updated_at': 'DESC'})
    op.create_index('idx_channel_conversations_updated_at', 'channel_conversations', ['updated_at'], unique=False, postgresql_ops={'updated_at': 'DESC'})
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_stripe_subscription_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_stripe_customer_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_status'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_plan_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index('uq_user_period', table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_user_id'), table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
