"""add model field to channel_conversations

Revision ID: ccbac5e5315e
Revises: 272a03552c78
Create Date: 2025-11-05 20:08:17.824614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbac5e5315e'
down_revision: Union[str, Sequence[str], None] = '272a03552c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_conversations', sa.Column('model', sa.String(length=50), server_default='claude-haiku-4.5', nullable=False))
    op.drop_index(op.f('idx_channel_conversations_updated_at'), table_name='channel_conversations')
    op.create_index('idx_channel_conversations_updated_at', 'channel_conversations', ['updated_at'], unique=False, postgresql_ops={'updated_at': 'DESC'})
    op.create_index(op.f('ix_channel_conversations_model'), 'channel_conversations', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_conversations_model'), table_name='channel_conversations')
    op.drop_index('idx_channel_conversations_updated_at', table_name='channel_conversations', postgresql_ops={'updated_at': 'DESC'})
    op.create_index(op.f('idx_channel_conversations_updated_at'), 'channel_conversations', [sa.literal_column('updated_at DESC')], unique=False)
    op.drop_column('channel_conversations', 'model')
    # ### end Alembic commands ###
